Logs in mount root. After some partition changes sometimes jffs refused to mount. To understand what it was

diff --git a/package/base-files/files/lib/preinit/80_mount_root b/package/base-files/files/lib/preinit/80_mount_root
--- a/package/base-files/files/lib/preinit/80_mount_root
+++ b/package/base-files/files/lib/preinit/80_mount_root
@@ -35,6 +35,10 @@ compose_rootfs_mount_options() {
 
 do_mount_root() {
 	mount_root start "$(compose_rootfs_mount_options)"
+	code="$(echo $?)"
+	if [ code != "0" ]; then
+		echo "mount_root failed: $code"
+	fi
 	boot_run_hook preinit_mount_root
 	[ -f /sysupgrade.tgz -o -f /tmp/sysupgrade.tar ] && {
 		echo "- config restore -"
